### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by james77777778** [james77777778/keras-aug#2]
The current focus of this repository is on 2D augmentations, such as geometry, intensity, mixing, and regularization. Version 0.1.0 will be released once it can reproduce all augmentations in YOLOv8 and existing KerasCV augmentations.

### Auto

- [x] RandAugment
- [x] RepeatedAugment
- [x] TrivialAugmentWide

###  Geometry

- [x] CenterCrop
- [x] PadIfNeeded
- [x] RandomAffine (yolov8: RandomPerspective)
- [x] RandomCrop
- [x] RandomCropAndResize (albumentations: RandomResizedCrop)
- [x] RandomFlip
- [x] RandomRotate
- [x] RandomZoomAndCrop
- [x] Resize (`crop_to_aspect_ratio`, `pad_to_aspect_ratio`, yolov8: LetterBox)
- [x] RandomResize (yolov5: multi-scale training)

### Intensity

- [x] AutoContrast
- [x] ChannelShuffle
- [x] Equalize
- [x] Grayscale
- [x] Invert
- [x] Normalize
- [x] RandomBlur
- [x] RandomChannelShift
- [x] RandomCLAHE (isears/tf_clahe)
- [x] RandomColorJitter (albumentations: ColorJitter)
- [x] RandomGamma
- [x] RandomGaussianBlur
- [x] RandomHSV
- [x] RandomJpegQuality (albumentations: ImageCompression)
- [x] RandomPosterize (a random version of keras_cv: Posterization)
- [x] RandomSharpness
- [x] RandomSolarize (keras_cv: Solarization)
- [x] ~~RandomMedianBlur (not going to support)~~
- [x] Rescale

### Mix

- [x] AugMix
- [x] CutMix
- [ ] FourierMix
- [x] ~~RandomCopyPaste  (not going to support)~~
- [x] MixUp
- [x] MosaicYOLOV8 (an improved version of keras_cv: Mosaic)

### Regularization

- [x] ChannelDropout
- [x] RandomCutout
- [x] RandomErase
- [x] RandomGridMask

### Utility

- [x] Identity
- [x] RandomApply
- [x] RandomChoice

### Base

- [x] VectorizedBaseRandomLayer

## Notes

KerasAug will not support RandomMedianBlur due to the limitations of the implementation of tfa.image.median_filter2d, which uses tf.image.extract_patches and cannot support dynamic filter size.

KerasAug cannot support RandomCopyPaste augmentation until the data structure for instance segmentation is clarified.
